# Generated by Django 4.0.5 on 2022-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_art_url',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
