# Generated by Django 4.0.5 on 2022-07-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_rename_artist_other_album_artist_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_fk',
        ),
        migrations.AddField(
            model_name='album',
            name='new_artist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='albums.artist'),
        ),
    ]
