# Generated by Django 4.0.5 on 2022-07-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_remove_album_artist_fk_album_new_artist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_fk',
        ),
    ]
